[package]
name = "vibeos-vsh"
version = "0.1.0"
edition = "2021"

[features]
default = ["pci-usb-help"]
pci-usb-help = []
network = []
file-tree = ["dep:vibeos-file-store"]

[dependencies]
vibeos-core = { path = "../../core" }
vibeos-file-store = { path = "../../services/file-store", optional = true }
