[workspace]
resolver = "2"
members = ["blob-format", "storage-device", "segment-format", "durable-format", "random", "runtime/riscv", "core", "compiler", "hal", "boards/qemu-virt", "boards/milkv-duo", "drivers/dwmac-net", "drivers/dwc2-host", "drivers/milkv-duo-led", "drivers/pci", "drivers/sdhci-blk", "drivers/virtio-blk", "drivers/virtio-core", "drivers/virtio-mmio", "drivers/virtio-net", "drivers/virtio-rng", "drivers/xhci", "components/net-api", "components/net-echo", "components/net-protocol", "components/netstack", "components/sshd", "components/vsh", "services/authority-store", "services/object-store", "services/program-store", "services/ssh-identity", "policy/image", "acceptance/kernel-tests", "kernel", "firmware/qemu-virt", "firmware/milkv-duo"]
exclude = ["vendor/sunset"]

[profile.dev]
panic = "abort"
opt-level = 1

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
debug = true
