#!/usr/bin/env python3
"""Compare ported Wasmtime RISC-V code generation with pinned upstream."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
from wasmtime.reference import compiler_reference
ROOT = Path(__file__).resolve().parents[1]

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--work', type=Path, default=ROOT/'target/wasmtime-codegen')
    p.add_argument('--module', type=Path, action='append')
    args = p.parse_args()
    work = args.work.resolve(); work.mkdir(parents=True, exist_ok=True)
    ref = work/'upstream'; (ref/'src').mkdir(parents=True, exist_ok=True)
    (ref/'Cargo.toml').write_text('''[package]
name = "wasmtime-codegen-reference"
version = "0.0.0"
edition = "2024"
[workspace]
[dependencies]
wasmtime-environ = { version = "=48.0.0", default-features = false, features = ["compile", "component-model"] }
wasmtime-cranelift = { package = "wasmtime-internal-cranelift", version = "=48.0.0" }
cranelift-codegen = { version = "=0.135.0", default-features = false, features = ["riscv64"] }
wasmparser = { version = "=0.254.0", default-features = false, features = ["features", "validate", "component-model"] }
''')
    (ref/'src/main.rs').write_bytes((ROOT/'wasmtime-runtime/examples/compile.rs').read_bytes())
    # Keep target correctness fixes identical while comparing std/core-alloc.
    compiler = compiler_reference(work)
    with (ref/'Cargo.toml').open('a') as manifest:
        manifest.write('\n[patch.crates-io]\ncranelift-codegen = { path = ' + json.dumps(str(ROOT/'vendor/wasmtime-48/cranelift-codegen')) + ' }\n')
        manifest.write('wasmtime-internal-cranelift = { path = ' + json.dumps(str(compiler)) + ' }\n')
    if not (ref/'Cargo.lock').exists():
        (ref/'Cargo.lock').write_bytes((ROOT/'tools/coremark-engines/Cargo.lock').read_bytes())
    subprocess.run(['cargo','metadata','--format-version','1','--offline','--manifest-path',str(ref/'Cargo.toml')],check=True,stdout=subprocess.DEVNULL)
    env = dict(os.environ, CARGO_TARGET_DIR=str(ROOT/'target/wasmtime-platform'))
    commands = [
        ['cargo','run','--locked','--offline','--manifest-path',str(ROOT/'wasmtime-runtime/Cargo.toml'),'--features','compiler','--example','compile','--'],
        ['cargo','run','--locked','--offline','--manifest-path',str(ref/'Cargo.toml'),'--'],
    ]
    modules = args.module or [ROOT/'target/coremark-wasi/coremark.wasm']
    invalid = work/'invalid.wasm'; invalid.write_bytes(b'\x00asm\xff\xff\xff\xff')
    records = []
    for index, module in enumerate([*modules, invalid]):
        outputs = []
        for mode, command in zip(('ported','upstream'), commands):
            run = subprocess.run([*command,str(module.resolve()),str(work/f"{index}-{mode}-code")],env=env,capture_output=True)
            (work/f'{index}-{mode}.stdout').write_bytes(run.stdout)
            (work/f'{index}-{mode}.stderr').write_bytes(run.stderr)
            outputs.append(run)
        if module == invalid:
            assert all(x.returncode != 0 and b'module translation' in x.stderr for x in outputs)
        else:
            assert all(x.returncode == 0 for x in outputs), f'inspect {work}'
            assert outputs[0].stdout == outputs[1].stdout
            left = {p.name:p.read_bytes() for p in (work/f"{index}-ported-code").iterdir()}
            right = {p.name:p.read_bytes() for p in (work/f"{index}-upstream-code").iterdir()}
            assert left and left == right, "generated bytes or relocation records differ"
        records.append(dict(module=str(module),sha256=hashlib.sha256(module.read_bytes()).hexdigest(),accepted=module!=invalid,summary=outputs[0].stdout.decode()))
    (work/'results.json').write_text(json.dumps(dict(reference='upstream 48.0.0 plus riscv64-fs1-abi.patch and riscv64-inline-copy.patch',scope='all function code bytes and relocation records; not linked or executed',modules=records),indent=2)+'\n')
    print(json.dumps(records,indent=2))
if __name__ == '__main__': main()
